timeline
    title Timeline for Timothy Mix
    section French and Indian War
        Year 1755 : Served as Surgeon's Mate
        Year 1758 : Service description?
    section American Revolution
        Year 1775 : The shot heard 'round the world
        Year 1776 : The Declaration of Independence
